#!/bin/bash

# Family Portfolio - Project Overview
# Shows the clean project structure

echo "📁 Family Portfolio - Clean Project Structure"
echo "============================================="
echo ""

echo "📊 PROJECT OVERVIEW:"
echo "==================="
echo "Total Projects: 3 microservices"
echo "Architecture: Decoupled containerized services"
echo "Network: Docker external network (family_network)"
echo ""

echo "🏗️  PROJECT STRUCTURE:"
echo "======================"
tree -I 'node_modules|__pycache__|*.pyc|build|dist|logs|uploads' . 2>/dev/null || {
    echo "family-portfolio-projects/"
    echo "├── 🌐 family-portfolio-frontend/    # React.js UI"
    echo "│   ├── src/                        # React components"
    echo "│   ├── public/                     # Static assets"
    echo "│   ├── Dockerfile                  # Frontend container"
    echo "│   ├── docker-compose.yml          # Frontend service"
    echo "│   ├── package.json                # Node dependencies"
    echo "│   └── README.md                   # Frontend docs"
    echo "│"
    echo "├── 🖥️  family-portfolio-backend/     # FastAPI REST API"
    echo "│   ├── app/                        # Python application"
    echo "│   ├── scripts/                    # Database scripts"
    echo "│   ├── tests/                      # Unit tests"
    echo "│   ├── Dockerfile                  # Backend container"
    echo "│   ├── docker-compose.yml          # Backend service"
    echo "│   ├── requirements.txt            # Python dependencies"
    echo "│   └── README.md                   # Backend docs"
    echo "│"
    echo "├── 🗄️  family-portfolio-database/    # PostgreSQL DB"
    echo "│   ├── init/                       # DB initialization"
    echo "│   ├── backups/                    # Backup location"
    echo "│   ├── docker-compose.yml          # Database service"
    echo "│   └── README.md                   # Database docs"
    echo "│"
    echo "├── 🚀 start-all.sh                 # Start all services"
    echo "├── 🛑 stop-all.sh                  # Stop all services"
    echo "├── 📊 status.sh                    # Check service status"
    echo "├── 📋 logs.sh                      # View service logs"
    echo "└── 📚 README.md                    # Main documentation"
}

echo ""
echo "📦 CORE FILES PER PROJECT:"
echo "========================="
echo ""
echo "Frontend (Essential files only):"
echo "  ✅ src/App.js - Main React application"
echo "  ✅ public/index.html - HTML template"
echo "  ✅ package.json - Dependencies"
echo "  ✅ Dockerfile - Container definition"
echo "  ✅ docker-compose.yml - Service config"
echo ""
echo "Backend (Essential files only):"
echo "  ✅ app/main.py - FastAPI application"
echo "  ✅ requirements.txt - Python dependencies"
echo "  ✅ Dockerfile - Container definition"
echo "  ✅ docker-compose.yml - Service config"
echo ""
echo "Database (Essential files only):"
echo "  ✅ init/01-init.sql - Basic setup"
echo "  ✅ init/02-schema.sql - Database schema"
echo "  ✅ docker-compose.yml - Service config"
echo ""

echo "🎯 QUICK COMMANDS:"
echo "=================="
echo "./start-all.sh     # Start all services"
echo "./stop-all.sh      # Stop all services"
echo "./status.sh        # Check service status"
echo "./logs.sh          # View logs"
echo "./overview.sh      # Show this overview"
echo ""

echo "🌐 APPLICATION URLS (when running):"
echo "==================================="
echo "Frontend:  http://localhost:3000"
echo "Backend:   http://localhost:8000"
echo "API Docs:  http://localhost:8000/docs"
echo "Database:  localhost:5432"